## Check for convergence

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df = pd.read_csv('data.csv', delimiter=";")

In [12]:
df

,Step,Time[fs],Kin.[a.u.],Temp[K],Pot.[a.u.],Cons Qty,Used time
0,0,0.0,0.180983,300.000000,-1.078062,-0.897078,0.000000
1,1,2.0,0.121293,201.057025,-1.102842,-0.981563,0.074366
2,2,4.0,0.123079,204.016606,-1.105215,-0.981601,0.024285
3,3,6.0,0.133561,221.392764,-1.112484,-0.981711,0.023845
4,4,8.0,0.146926,243.546037,-1.123009,-0.981870,0.023589
...,...,...,...,...,...,...,...
9997,9997,19994.0,0.202173,335.123636,-1.126845,-0.981863,0.022228
9998,9998,19996.0,0.194444,322.312350,-1.121401,-0.981799,0.022546
9999,9999,19998.0,0.187565,310.909497,-1.115293,-0.981735,0.021653
10000,10000,20000.0,0.180572,299.317451,-1.109485,-0.981671,0.021737
10001,},NaN,NaN,NaN,NaN,NaN,NaN